[basics]
name = "John Doe"
label = "Programmer"
image_path = ""
email = "john@jmail.com"
phone = "(912) 555-4321"
url = "https://johndoe.com/"
summary = "A summary of John Doe..."

[basics.location]
address = "2712 Broadway St"
postal_code = "CA 94115"
city = "San Francisco"
country_code = "US"
region = "California"

[[basics.profiles]]
network = "X/Twitter"
username = "john"
url = "https://x.com/john"

[[work]]
name = "Company"
position = "President"
url = "https://company.com/"
start_date = "2013-01-01"
end_date = "2014-01-01"
summary = "Lorem Ipsum..."
highlights = [
    "Started the company",
]

[[volunteer]]
organization = "Organisation"
position = "Volunteer"
url = "https://organisation.com/"
start_date = "2012-01-01"
end_date = "2013-01-01"
summary = "Dolor sit amet..."
highlights = [
    "Awarded 'Volunteerr of the Month'",
]

[[education]]
institution = "University"
url = "https://university.com/"
area = "Software Development"
study_type = "Bachelor"
start_date = "2011-01-01"
end_date = "2013-01-01"
score = "4.0"
courses = [
    "DB1101 - Basic SQL",
]

[[awards]]
title = "Award"
date = "2014-11-01"
awarder = "Company"
summary = "There is no spoon."

[[certificates]]
name = "Certificate"
date = "2021-11-07"
issuer = "Company"
url = "https://certificate.com/"

[[publications]]
name = "Publication"
publisher = "Company"
release_date = "2014-10-01"
url = "https://publication.com/"
summary = "Description..."

[[skills]]
name = "Web Development"
level = "Master"
keywords = [
    "HTML",
    "CSS",
    "JavaScript",
]

[[languages]]
language = "English"
fluency = "Native speaker"

[[interests]]
name = "Wildlife"
keywords = [
    "Crabs",
    "Unicorns",
]

[[references]]
name = "Jane Doe"
reference = "Reference..."

[[projects]]
name = "Project"
start_date = "2019-01-01"
end_date = "2021-01-01"
description = "Description..."
highlights = [
    "Won award at AIHacks 2016",
]
url = "https://project.com/"
